subugoe/typo3-tmpl_fidaac

README.md

Minor fix for README.md, mostly to test if protected branch is working.

Fix Readme Header

---

Configuration/TypoScript/020_Extensions/Pazpar2.t3s
Configuration/TypoScript/setup.txt

Copy of the configuration from fileadmin to site package
Part of AAC-127

pazpar2 configuration for the homepage

---

Configuration/TypoScript/020_Extensions/Pazpar2.t3s
Configuration/TypoScript/030_Page/Page.t3s
Resources/Public/Css/main.css

Configuration for the pages with extensions parzpar2 and nkwgok.
Files from fileadmin copied in the site package.
Resolves AAC-127

Transfer the configuration for subject search and guide

---

tests/test-local-ezbrequest.js

Related to: AAC-133 and AAC-164

Add tests for ezbrequest

---

Configuration/TypoScript/Elements/001_Config.t3s
Configuration/TypoScript/Elements/040_Languages.t3s
Resources/Private/Templates/Partials/Header.html

and a cObject as language switcher.
Resolves AAC-272

Set english as default language and german as second language

---

Configuration/TypoScript/Elements/030_Page.t3s
Resources/Private/Scss/App.scss
Resources/Private/Scss/Base.scss
Resources/Private/Scss/Categories.scss
Resources/Private/Scss/Settings.scss
Resources/Private/Templates/Partials/Logo.html
Resources/Private/Templates/Partials/Main.html
Resources/Private/Templates/Partials/Navigation.html
Resources/Public/Css/main.css
package.json

Show categories of pages

---

Resources/Private/Scss/Header.scss
Resources/Public/Css/main.css

Adjust color of language switcher

---

Resources/Private/Scss/Base.scss
Resources/Public/Css/main.css

Visualize links in paragraphs and add font-weight

---

Configuration/PageTS/RTE.txt
Configuration/PageTS/Sitepackage.txt
Configuration/PageTS/TCEFORM.txt

Also rename the layouts 1-4  in heading 1-4
resolves AAC-343

Hide unnecessary buttons for the editors in the RTE toolbar

---

Configuration/TypoScript/Elements/010_Extensions/050_News.t3s
Configuration/TypoScript/Elements/030_Page.t3s
Configuration/TypoScript/Static/setup.txt
Configuration/TypoScript/setup.txt
Resources/Private/Language/locallang_news.xml
Resources/Private/Scss/App.scss
Resources/Private/Scss/Base.scss
Resources/Private/Scss/News.scss
Resources/Private/Templates/Extensions/News/Partials/Category/Items.html
Resources/Private/Templates/Extensions/News/Partials/List/Item.html
Resources/Private/Templates/Partials/Header.html
Resources/Private/Templates/Partials/Main.html
Resources/Private/Templates/Partials/Navigation.html
Resources/Public/Css/main.css

Implement design for news list mode

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Resources/Private/Scss/Navigation.scss
Resources/Private/Templates/Partials/Navigation.html
Resources/Public/Css/main.css

Add third menu level

---

Configuration/TypoScript/Elements/010_Extensions/010_pazpar2.t3s

Configure the overall catalogue search with pazpar2

---

Configuration/TypoScript/Elements/030_Page.t3s

Add missing JS libraries for pazpar2

---

Configuration/TypoScript/Elements/030_Page.t3s
Resources/Private/Scss/App.scss
Resources/Private/Scss/Base.scss
Resources/Private/Scss/Flex.scss
Resources/Private/Scss/Navigation.scss
Resources/Public/Css/main.css
Resources/Public/JavaScript/main.js

Add button to first level navigation

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Resources/Private/Scss/App.scss
Resources/Private/Scss/Flex.scss
Resources/Private/Scss/Header.scss
Resources/Private/Scss/Main.scss
Resources/Private/Scss/Navigation.scss
Resources/Private/Scss/News.scss
Resources/Private/Scss/Page.scss
Resources/Private/Templates/Extensions/News/Partials/List/Item.html
Resources/Private/Templates/Partials/Header.html
Resources/Private/Templates/Partials/Main.html
Resources/Private/Templates/Partials/Navigation.html
Resources/Public/Css/main.css
Resources/Public/JavaScript/main.js

Scrolled content with reduced, fixed header

---

Resources/Private/Templates/Extensions/News/Partials/List/Item.html

Align meta infos in news detail view

---

Resources/Private/Templates/Extensions/News/Templates/News/Detail.html

The automatically generated social media buttons in the detailed
view.
Resolves AAC-371

Delete the social media buttons from the News template

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Configuration/TypoScript/Elements/030_Page.t3s
Resources/Private/Scss/App.scss
Resources/Private/Scss/Flex.scss
Resources/Private/Scss/Header.scss
Resources/Private/Scss/Main.scss
Resources/Private/Scss/Navigation.scss
Resources/Private/Scss/News.scss
Resources/Private/Scss/Page.scss
Resources/Private/Scss/Scrolled.scss
Resources/Private/Scss/Sitemap.scss
Resources/Private/Templates/Default.html
Resources/Private/Templates/Partials/Header.html
Resources/Private/Templates/Partials/Main.html
Resources/Private/Templates/Partials/Navigation.html
Resources/Private/Templates/Partials/Sitemap.html
Resources/Public/Css/main.css
Resources/Public/JavaScript/main.js
Resources/Public/JavaScript/mediaChanges.js

Sitemap implemented, Header fixed and span positioning enhanced

---

Configuration/TypoScript/Elements/010_Extensions/010_pazpar2.t3s

Related to: AAC-355
See Jira for instructions

Subject search configuration

---

Resources/Private/Scss/Page.scss
Resources/Public/Css/main.css

Style list elements

---

Resources/Private/Scss/DoubleColumn.scss
Resources/Public/Css/main.css

Align items in double colums on top

---

Resources/Private/Scss/Page.scss
Resources/Public/Css/main.css

Show links in lists

---

Resources/Private/Templates/Partials/Header.html

Link logo to start page

---

Resources/Private/Templates/Partials/Header.html

Link image, too

---

Resources/Private/Scss/Main.scss
Resources/Public/Css/main.css

Use multicolumn and increase default text width

---

Configuration/System/realurl_conf.php

Include extra config file in typo3conf

---

Resources/Private/Scss/Page.scss
Resources/Public/Css/main.css
Resources/Public/JavaScript/mediaChanges.js

Make headings responsive

---

Resources/Private/Scss/News.scss
Resources/Public/Css/main.css

Remove +-sign in news pagination

---

.gitignore

Remove main.css from commits

---

Configuration/TypoScript/Elements/030_Page/040_TwoColumnContent.t3s
Resources/Private/Scss/Main.scss
Resources/Private/Templates/Extensions/FluidStyledContent/Resources/Private/Templates/Textmedia.html
Resources/Public/Css/main.css
Resources/Public/JavaScript/content.js

Implement multicolumn (works not with images so far)

---

Configuration/TypoScript/Elements/010_Extensions/050_News.t3s
Resources/Private/Templates/Extensions/News/Templates/News/List.atom
Resources/Private/Templates/Extensions/News/Templates/News/List.xml

Basic configuration for RSS

---

Configuration/PageTS/RTE.txt
Resources/Private/Scss/App.scss
Resources/Private/Scss/DescriptionList.scss
Resources/Private/Scss/Mixins.scss
Resources/Public/Css/main.css

Implement definition list

---

Configuration/TypoScript/Elements/030_Page/010_Page.t3s
Resources/Private/Scss/Header.scss
Resources/Private/Scss/Mixins.scss
Resources/Private/Scss/Navigation.scss
Resources/Private/Scss/Page.scss
Resources/Private/Templates/Partials/Header.html
Resources/Private/Templates/Partials/Navigation.html
Resources/Public/JavaScript/Header.js
Resources/Public/JavaScript/main.js
Resources/Public/JavaScript/mediaChanges.js

Implement home header for L and M sizes

---

Resources/Private/Scss/Page.scss

Implement small headings

---

Resources/Private/Scss/DescriptionList.scss

Narrower title in definition lists

---

Configuration/TypoScript/Elements/030_Page/010_Page.t3s
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Scss/App.scss
Resources/Private/Scss/Header.scss
Resources/Private/Scss/Last.scss
Resources/Private/Scss/Mixins.scss
Resources/Private/Templates/Default.html
Resources/Private/Templates/Partials/Last.html

Implement last row

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Resources/Private/Scss/Footer.scss

Fix line break when no subpages

---

Resources/Private/Scss/Main.scss
Resources/Private/Templates/Partials/Main.html

Make footer sticky

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Resources/Private/Scss/Footer.scss

Implement footer in S

---

Resources/Private/Scss/News.scss
Resources/Private/Templates/Partials/Main.html

Prohibit new line in news categories

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Configuration/TypoScript/Elements/030_Page/010_Page.t3s
Resources/Private/Scss/App.scss
Resources/Private/Scss/Breadcrumbs.scss
Resources/Private/Scss/Navigation.scss
Resources/Private/Scss/Settings.scss
Resources/Private/Templates/Partials/Navigation.html
Resources/Public/JavaScript/Header.js
Resources/Public/JavaScript/Main.js
Resources/Public/JavaScript/Navigation.js

Implement alternative Menu with arrows an JavaScript in L

---

Configuration/TypoScript/Elements/030_Page/010_Page.t3s
Resources/Private/Scss/Header.scss
Resources/Public/JavaScript/Header.js
Tests/test-header.js

Implement header for home page in S

---

Resources/Private/Scss/News.scss

Don't break lines in categories

---

Configuration/PageTS/RTE.txt
Resources/Private/Scss/App.scss
Resources/Private/Scss/Content.scss
Resources/Private/Scss/Main.scss
Resources/Public/Css/rte.css

Implement literature lists

---

Resources/Private/Scss/Navigation.scss
package.json

Related to: AAC-580
... and include npmrc in package.json for automated use

Change font size in menu

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Resources/Private/JavaScript/Navigation.Js

Toggle SVG in first level navigation

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Resources/Private/JavaScript/Navigation.Js
Resources/Private/Scss/Navigation.scss

Emphasize clicked navigation sublevel items

---

Resources/Private/JavaScript/Navigation.Js

Hide the menu when clicked anywhere in the content

---

Resources/Private/JavaScript/Navigation.Js

Show whole path when menu element clicked

---

Configuration/TypoScript/Elements/010_Extensions/050_News.t3s
Configuration/TypoScript/Elements/010_Extensions/080_Misc.t3s
Configuration/TypoScript/Elements/030_Page/010_Page.t3s

Limit media type of regular CSS

---

Configuration/PageTS/Sitepackage.txt
Configuration/PageTS/TCEMAIN.txt

Make sure, that editors can see new pages and have all rights
Related to: AAC-591

Set default group for pages

---

Resources/Private/Scss/Main.scss

Adjust font size

---

Resources/Private/Scss/Page.scss

Adjust font weight

---

Resources/Private/Scss/Main.scss

Remove css vendor prefixes

---

bs-config.js
package.json

Add browser sync to npm scripts

---

Configuration/TypoScript/Elements/030_Page/010_Page.t3s
build.js
package.json

AAA-615 load jquery locally

---

Resources/Private/Scss/App.scss
Resources/Private/Scss/Tools.scss
Resources/Private/Templates/Partials/Header.html

Fix missing home link

---

Configuration/PageTS/Permissions.txt
Configuration/PageTS/RTE.txt
Configuration/PageTS/Sitepackage.txt
ext_tables.php

Define backend permissions in extension

---

Resources/Private/JavaScript/Navigation.Js
Resources/Private/Scss/_navigation.scss
Resources/Private/Scss/_page.scss

Open menu with hover over arrow

---

Resources/Private/Scss/_main.scss

Related to: AAC-553 and AAC-649

Re-implement literatur lists and decrease font-size

---

Configuration/TypoScript/Elements/020_Navigation.t3s
Resources/Private/JavaScript/Images.Js
Resources/Private/JavaScript/Navigation.Js
Resources/Private/Scss/_navigation.scss

Show submenus already on hover of text

---

Resources/Private/Templates/Extensions/News/Templates/News/Detail.html

Show the detail view of a news in version 6.0.0
